### PR TITLE
Implemented more webnetes functions and models

### PR DESCRIPTION
**Pull request by lucas-goldner**

### CODE REVIEW

**Comment by pojntfx** [comment]
Can't build the project: `[ERROR] JSBody method space.nebulark.jnebulark.bindings.WebnetesNode._close()V declares 0 parameters, but annotation specifies 4
    at space.nebulark.jnebulark.bindings.WebnetesNode._close
    at space.nebulark.jnebulark.bindings.WebnetesNode.close(WebnetesNode.java:31)
    at space.nebulark.jnebulark.WebnetesConfigView.closeNode(WebnetesConfigView.java:79)
    at space.nebulark.jnebulark.WebnetesConfigView.closeAndOpenNode(WebnetesConfigView.java:68)
    at java.util.function.Consumer$proxy$4_3_12.accept(webnetesConfig.html:511)
    at org.teavm.flavour.components.events.BaseEventBinder$setHandler$lambda$_2_0.handleEvent(BaseEventBinder.java:44)
    at org.teavm.flavour.components.events.BaseEventBinder$setHandler$lambda$_2_0.handleEvent$exported$0`

**Comment by pojntfx** [comment]
To reproduce: `mvn clean install`

**Comment by lucas-goldner** [comment]
I found the issues and fixxed it

**Comment by pojntfx** [comment]
LGTM!

**Pull request merged**
